# Generated by Django 5.1 on 2024-08-23 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="post",
            name="categoria",
        ),
    ]
